# permissions for end users to edit workloadschedules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: workloadschedule-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: workload-scheduler-operator
    app.kubernetes.io/part-of: workload-scheduler-operator
    app.kubernetes.io/managed-by: kustomize
  name: workloadschedule-editor-role
rules:
- apiGroups:
  - workload-scheduler.bennsimon.github.io
  resources:
  - workloadschedules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workload-scheduler.bennsimon.github.io
  resources:
  - workloadschedules/status
  verbs:
  - get
