---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "workload-scheduler-operator.labels" . | nindent 4 }}
  name: {{ include "workload-scheduler-operator.fullname" . }}

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "workload-scheduler-operator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "workload-scheduler-operator.fullname" . }}
    namespace: {{ .Release.Namespace }}
